# Generated by Django 4.2.7 on 2023-11-13 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livechat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
